import type { Metadata } from "next";
import { Poppins, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/page-header";
import { MainNav } from "@/components/main-nav";

const font = Poppins({
  subsets: ['latin'],
  weight:['400']
})

export const metadata: Metadata = {
  title: "Casino Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {/* <div>
         {children}
        </div> */}
        
        <div className="container mx-auto md:flex">
        <MainNav />
        <div>
          {children}
        </div>
      </div>

      </body>
    </html>
  );
}
